imports:
    - { resource: parameters.yml }
    - { resource: parametros.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    photo.proveedor: %kernel.root_dir%/../photos/proveedor/

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#Parametros para cambiar apariencia de la plataforma    
    globals:
        urlParam: '%app.urlParam%'
        pais: '%app.pais%'
        nombre: '%app.nombre%'
        tituloHome: '%app.tituloHome%'

        #serverMesages
        serverOffline: '%app.serverOffline%'
        serverDuplicateName: '%app.serverDuplicateName%'
        serverMsgSave: '%app.serverMsgSave%'
        serverMsgUpdate: '%app.serverMsgUpdate%'
        serverMsgCancel: '%app.serverMsgCancel%'
        serverCancel: '%app.serverCancel%'
        serverMsgDelete: '%app.serverMsgDelete%'
        serverError: '%app.serverError%'
        
        #loginMessages
        usernameInvalidate: '%app.usernameInvalidate%'
        checkCaptcha: '%app.checkCaptcha%'
        invalidCaptcha: '%app.invalidCaptcha%'
        
        #form validations
        #requiredFields
        requiredFields: '%app.requiredFields%'
        #cancelLabel
        cancelLabel: '%app.cancelLabel%'
        #removeLabel
        removeLabel: '%app.removeLabel%'
        #cancelButtonText
        cancelButtonText: '%app.cancelButtonText%'
        #confirmButtonText
        confirmButtonText: '%app.confirmButtonText%'
        #alternateconfirmButtonText
        alternateconfirmButtonText: '%app.alternateconfirmButtonText%'
        #imageError
        imageError: '%app.imageError%'
        #requiredFields
        select2Label: '%app.select2Label%'
        
        editPass: '%app.editPass%'
        showLog: '%app.showLog%'
        settings: '%app.settings%'
        logOut: '%app.logOut%'

        #datatables
        dtInfo: '%app.dtInfo%'
        dtInfoEmpty: '%app.dtInfoEmpty%'
        dtEmptyTable: '%app.dtEmptyTable%'
        dtNext: '%app.dtNext%'
        dtPrev: '%app.dtPrev%'
        dtProcessing: '%app.dtProcessing%'
        dtSearch: '%app.dtSearch%'
        dtLengthMenu: '%app.dtLengthMenu%'
        dtZeroRecords: '%app.dtZeroRecords%'


        #Botones
        add: '%app.add%'
        delete: '%app.delete%'
        back: '%app.back%'
        show: '%app.show%'
        action: '%app.action%'
        save: '%app.save%'
        cancel: '%app.cancel%'

        #Tooltips
        accountsTooltip: '%app.accountsTooltip%'
        saleStagesTooltip: '%app.saleStagesTooltip%'
        activitiesTooltip: '%app.activitiesTooltip%'
        calendarTooltip: '%app.calendarTooltip%'
        settingsTooltip: '%app.settingsTooltip%'
        reportsTooltip: '%app.reportsTooltip%'

        #icons
        accountsIcon: '%app.accountsIcon%'
        saleStagesIcon: '%app.saleStagesIcon%'
        activitiesIcon: '%app.activitiesIcon%'
        calendarIcon: '%app.calendarIcon%'
        settingsIcon: '%app.settingsIcon%'
        reportsIcon: '%app.reportsIcon%'
        
        #Wizard de configuracion inicial
        tituloWizard: '%app.tituloWizard%'
        encabezadoWizard: '%app.encabezadoWizard%'
        step1Wizard: '%app.step1Wizard%'
        step2Wizard: '%app.step2Wizard%'
        step3Wizard: '%app.step3Wizard%'
        step4Wizard: '%app.step4Wizard%'
        btnSaveandContWizard: '%app.btnSaveandContWizard%'
        btnPreviousWizard: '%app.btnPreviousWizard%'
        btnSkipWizard: '%app.btnSkipWizard%'
        btnCompletedWizard: '%app.btnCompletedWizard%'

        #Encabezados panel
        pnHeadingLabelAdd: '%app.pnHeadingLabelAdd%'
        pnHeadingLabelEdit: '%app.pnHeadingLabelEdit%'

        #Etapas de ventas
        tituloEtapa: '%app.tituloEtapa%'
        menuEtapa: '%app.menuEtapa%'
        encabezadoEtapa: '%app.encabezadoEtapa%'
        descripcionEtapa: '%app.descripcionEtapa%'
        nameEtapa: '%app.nameEtapa%'
        probabilityEtapa: '%app.probabilityEtapa%'
        
        #Campanias
        tituloCampania: '%app.tituloCampania%'
        menuCampania: '%app.menuCampania%'
        encabezadoCampania: '%app.encabezadoCampania%'
        descripcionCampania: '%app.descripcionCampania%'
        nameCampania: '%app.nameCampania%'

        #Nivel de satisfaccion
        tituloSatisfaccion: '%app.tituloSatisfaccion%'
        menuSatisfaccion: '%app.menuSatisfaccion%'
        encabezadoSatisfaccion: '%app.encabezadoSatisfaccion%'
        descripcionSatisfaccion: '%app.descripcionSatisfaccion%'
        nameSatisfaccion: '%app.nameSatisfaccion%'

        #Proveedor
        tituloProveedor: '%app.tituloProveedor%'
        
        companiaNombreProveedor: '%app.companiaNombreProveedor%'
        menuProveedor: '%app.menuProveedor%'
        encabezadoProveedor: '%app.encabezadoProveedor%'
        descripcionProveedor: '%app.descripcionProveedor%'
        nameProveedor: '%app.nameProveedor%'
        nombreProveedor: '%app.nombreProveedor%'
        apellidoProveedor: '%app.apellidoProveedor%'
        tratoProveedor: '%app.tratoProveedor%'
        extensionProveedor: '%app.extensionProveedor%'
        emailProveedor: '%app.emailProveedor%'
        phoneProveedor: '%app.phoneProveedor%'
        direccionProveedor: '%app.direccionProveedor%'
        fotoProveedor: '%app.fotoProveedor%'
        ciudadProveedor: '%app.ciudadProveedor%'
        departamentoProveedor: '%app.departamentoProveedor%'
        tipoPersonaProveedor: '%app.tipoPersonaProveedor%'
        industriaProveedor: '%app.industriaProveedor%'
        sitioWebProveedor: '%app.sitioWebProveedor%'
        inputFileLabel: '%app.inputFileLabel%'
        
        #Tiempo notificaciones
        tituloTiempoNotificacion: '%app.tituloTiempoNotificacion%'
        menuTiempoNotificacion: '%app.menuTiempoNotificacion%'
        encabezadoTiempoNotificacion: '%app.encabezadoTiempoNotificacion%'
        descripcionTiempoNotificacion: '%app.descripcionTiempoNotificacion%'
        nameTiempoNotificacion: '%app.nameTiempoNotificacion%'
        duracionTiempoNotificacion: '%app.duracionTiempoNotificacion%'
        unidadTiempoNotificacion: '%app.unidadTiempoNotificacion%'
        minutosTiempoNotificacion: '%app.minutosTiempoNotificacion%'
        diasTiempoNotificacion: '%app.diasTiempoNotificacion%'
        mesesTiempoNotificacion: '%app.mesesTiempoNotificacion%'
        aniosTiempoNotificacion: '%app.aniosTiempoNotificacion%'


        #Tareas (actividades)
        tituloTareas: '%app.tituloTareas%'
        menuTareas: '%app.menuTareas%'
        encabezadoTareas: '%app.encabezadoTareas%'
        descripcionTareas: '%app.descripcionTareas%'
        descripcionFormTareas: '%app.descripcionFormTareas%'
        nameTareas: '%app.nameTareas%'
        tipoTareas: '%app.tipoTareas%'
        prioridadTareas: '%app.prioridadTareas%'
        estadoTareas: '%app.estadoTareas%'
        responsableTareas: '%app.responsableTareas%'
        recordatorioTareas: '%app.recordatorioTareas%'
        fechaInicioTareas: '%app.fechaInicioTareas%'
        fechaCancelTareas: '%app.fechaCancelTareas%'
        estado: '%app.estadoTareas%'
        fechaFinTareas: '%app.fechaFinTareas%'
        descripcionFormTareas: '%app.descripcionFormTareas%'
        prioridadTareas: '%app.prioridadTareas%'
        taskNoEdit: '%app.taskNoEdit%'
        
        #Tipo de cuenta (CRUD)
        tituloTipoCuenta: '%app.tituloTipoCuenta%'
        encabezadoTipoCuenta: '%app.encabezadoTipoCuenta%'
        descripcionTipoCuenta: '%app.descripcionTipoCuenta%'
        nameTipoCuenta: '%app.nameTipoCuenta%'

        #Fuentes de origen (CRUD)
        tituloFuenteOrigen: '%app.tituloFuenteOrigen%'
        encabezadoFuenteOrigen: '%app.encabezadoFuenteOrigen%'
        descripcionFuenteOrigen: '%app.descripcionFuenteOrigen%'
        nameFuenteOrigen: '%app.nameFuenteOrigen%'
        
        #Prioridad (CRUD)
        tituloPrioridad: '%app.tituloPrioridad%'
        encabezadoPrioridad: '%app.encabezadoPrioridad%'
        descripcionPrioridad: '%app.descripcionPrioridad%'
        namePrioridad: '%app.namePrioridad%'

        #Login
        tituloLogin: '%app.tituloLogin%'        
        usernameTxt: '%app.usernameTxt%'        
        passwordTxt: '%app.passwordTxt%'        
        
        
        
        
        perfil: '%app.perfil%'
        perfilPublico: '%app.perfilPublico%'
        verficarmeAbogado: '%app.verficarmeAbogado%'
        verficarmeNotario: '%app.verficarmeNotario%'
        miSuscripciones: '%app.miSuscripciones%'
        miEmpresa: '%app.miEmpresa%'
        ajustesCuenta: '%app.ajustesCuenta%'
        miBlog: '%app.miBlog%'
        centroPreguntas: '%app.centroPreguntas%'
        cambiarPass: '%app.cambiarPass%'
        abogadosReg: '%app.abogadosReg%'
        aprobacionAbogados: '%app.aprobacionAbogados%'
        aprobacionPagos: '%app.aprobacionPagos%'
        verificarAbogados: '%app.verificarAbogados%'
        verificarNotarios: '%app.verificarNotarios%'
        facturacion: '%app.facturacion%'
        aprobarPreguntas: '%app.aprobarPreguntas%'
        correoAdmin: '%app.correoAdmin%'
        promociones: '%app.promociones%'
        logoPanel: '%app.logoPanel%'
        logoColor: '%app.logoColor%'
        logoPublicidad: '%app.logoPublicidad%'
        logoRegistro: '%app.logoRegistro%'
        logoBlanco: '%app.logoBlanco%'
        correoInfo: '%app.correoInfo%'
        codigoParam: '%app.codigoParam%'
        coordenadasLatitud: '%app.coordenadasLatitud%'
        coordenadasLongitud: '%app.coordenadasLongitud%'
        facebook: '%app.facebook%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    ERPCRMBundle: ~
                dql:
                    datetime_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        IFNULL: DoctrineExtensions\Query\Mysql\IfNull

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
