imports:
    - { resource: parameters.yml }
    - { resource: parametros.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#Parametros para cambiar apariencia de la plataforma    
    globals:
        urlParam: '%app.urlParam%'
        pais: '%app.pais%'
        nombre: '%app.nombre%'
        tituloHome: '%app.tituloHome%'
        tituloDirectorio: '%app.tituloDirectorio%'
        tituloPreguntarGratis: '%app.tituloPreguntarGratis%'
        tituloRealizarPregunta: '%app.tituloRealizarPregunta%'
        tituloRespuesta: '%app.tituloRespuesta%'
        tituloPreguntas: '%app.tituloPreguntas%'
        tituloLogin: '%app.tituloLogin%'
        tituloRegistro: '%app.tituloRegistro%'
        tituloBlog: '%app.tituloBlog%'
        tituloBlogEntrada: '%app.tituloBlogEntrada%'
        tituloContacto: '%app.tituloContacto%'
        tituloRecomendar: '%app.tituloRecomendar%'
        tituloRecuperarContraseña: '%app.tituloRecuperarContraseña%'
        perfil: '%app.perfil%'
        perfilPublico: '%app.perfilPublico%'
        verficarmeAbogado: '%app.verficarmeAbogado%'
        verficarmeNotario: '%app.verficarmeNotario%'
        miSuscripciones: '%app.miSuscripciones%'
        miEmpresa: '%app.miEmpresa%'
        ajustesCuenta: '%app.ajustesCuenta%'
        miBlog: '%app.miBlog%'
        centroPreguntas: '%app.centroPreguntas%'
        cambiarPass: '%app.cambiarPass%'
        abogadosReg: '%app.abogadosReg%'
        aprobacionAbogados: '%app.aprobacionAbogados%'
        aprobacionPagos: '%app.aprobacionPagos%'
        verificarAbogados: '%app.verificarAbogados%'
        verificarNotarios: '%app.verificarNotarios%'
        facturacion: '%app.facturacion%'
        aprobarPreguntas: '%app.aprobarPreguntas%'
        correoAdmin: '%app.correoAdmin%'
        promociones: '%app.promociones%'
        logoPanel: '%app.logoPanel%'
        logoColor: '%app.logoColor%'
        logoPublicidad: '%app.logoPublicidad%'
        logoRegistro: '%app.logoRegistro%'
        logoBlanco: '%app.logoBlanco%'
        correoInfo: '%app.correoInfo%'
        codigoParam: '%app.codigoParam%'
        coordenadasLatitud: '%app.coordenadasLatitud%'
        coordenadasLongitud: '%app.coordenadasLongitud%'
        facebook: '%app.facebook%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    ERPCRMBundle: ~
                dql:
                    datetime_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        IFNULL: DoctrineExtensions\Query\Mysql\IfNull

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
