services:
#    erpcrm.example:
#        class: ERP\CRMBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    calendarListener:
        class: ERP\CRMBundle\Listener\CalendarEventListener
        arguments: 
            entityManagerMy: "@doctrine.orm.default_entity_manager"
            mail: '@mailer'
            templating: '@templating'
            security: "@security.context"
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }